# Generated by Django 6.0.2 on 2026-03-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_trip_budget_trip_group_size_itineraryactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryactivity',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
