# Generated by Django 5.0.6 on 2026-04-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_itineraryactivity_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('ACCOMMODATION', 'Accommodation'), ('ACTIVITIES', 'Activities & Tours'), ('MISC', 'Miscellaneous')], default='MISC', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='app.trip')),
            ],
        ),
    ]
