# Generated by Django 6.0.2 on 2026-04-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
