from rest_framework import serializers
from .models import User, Post, Comment, Like, Report, Trip, ItineraryActivity, Expense, Notification

class NotificationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Notification
        fields = '__all__'
        extra_kwargs = {'user': {'read_only': True}}

class UserSerializer(serializers.ModelSerializer):
    password = serializers.CharField(write_only=True)
    followers_count = serializers.IntegerField(source='followers.count', read_only=True)
    following_count = serializers.IntegerField(source='following.count', read_only=True)

    class Meta:
        model = User
        fields = [
            'id', 'username', 'email', 'password', 'role', 
            'profile_picture', 'bio', 'followers_count', 'following_count'
        ]

    def create(self, validated_data):
        user = User.objects.create_user(
            username=validated_data['username'],
            email=validated_data.get('email', ''),
            password=validated_data['password'],
            role=validated_data.get('role', 'USER')
        )
        return user


class CommentSerializer(serializers.ModelSerializer):
    user_name = serializers.ReadOnlyField(source='user.username')

    class Meta:
        model = Comment
        fields = '__all__'
        extra_kwargs = {'user': {'read_only': True}}


class PostSerializer(serializers.ModelSerializer):
    author_name = serializers.ReadOnlyField(source='author.username')
    author_id = serializers.ReadOnlyField(source='author.id')
    likes_count = serializers.IntegerField(source='likes.count', read_only=True)
    is_followed_by_me = serializers.SerializerMethodField(read_only=True)
    # This automatically fetches all comments related to this post
    comments = CommentSerializer(many=True, read_only=True)

    class Meta:
        model = Post
        fields = '__all__'
        extra_kwargs = {'author': {'read_only': True}}

    def get_is_followed_by_me(self, obj):
        request = self.context.get('request')
        if request and request.user.is_authenticated:
            return request.user.following.filter(id=obj.author.id).exists()
        return False


class ReportSerializer(serializers.ModelSerializer):
    reported_by_name = serializers.ReadOnlyField(source='reported_by.username')
    post_title = serializers.ReadOnlyField(source='post.title')

    class Meta:
        model = Report
        fields = '__all__'
        extra_kwargs = {'reported_by': {'read_only': True}}


class ActivitySerializer(serializers.ModelSerializer):
    class Meta:
        model = ItineraryActivity
        fields = '__all__'


class ExpenseSerializer(serializers.ModelSerializer):
    class Meta:
        model = Expense
        fields = '__all__'


class TripSerializer(serializers.ModelSerializer):
    # This automatically fetches all activities generated by the AI for this trip
    activities = ActivitySerializer(many=True, read_only=True)
    expenses = ExpenseSerializer(many=True, read_only=True)
    total_expenses = serializers.SerializerMethodField(read_only=True)

    class Meta:
        model = Trip
        fields = '__all__'
        extra_kwargs = {'user': {'read_only': True}}

    def get_total_expenses(self, obj):
        return sum(expense.amount for expense in obj.expenses.all())


class RegisterSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        extra_kwargs = {'password': {'write_only': True}}

    def create(self, validated_data):
        return User.objects.create_user(**validated_data)